### ISSUE TITLE
Add Config for temp settings for the API calls

### ISSUE THREAD

**Issue by markokraemer** [datastax/astra-assistants-api#16]

**Comment by phact** [comment]
Thinking we do this at run creation, I'll take a stab at it.

**Comment by phact** [comment]
got done in [v0.15.5 - temperature support](https://github.com/phact/streaming-assistants/commit/b6d31724039be36846d5299963bf358418359239)

here's an example https://github.com/datastax/astra-assistants-api/blob/main/tests/streaming-assistants/test_run.py#L16
