### ISSUE TITLE
Permission Denied Error when using with_options in OpenAI client

### ISSUE THREAD

**Issue by VRSEN** [datastax/astra-assistants-api#21]
### Description
When attempting to create a file using the OpenAI Client with custom options set via `with_options`, a `PermissionDeniedError` is thrown indicating a missing authentication token in the header.

### Steps to Reproduce
1. Initialize the OpenAI Client and patch it.
2. Attempt to create a file using the following code:
   ```python
   file_id = self.client.with_options(
       timeout=80 * 1000,  # Set a custom timeout
   ).files.create(file=f, purpose="assistants").id
   ```
3. Observe the `PermissionDeniedError` with a 403 status code indicating a missing 'astra-api-token'.

### Expected Behavior
The file creation should proceed without any permission errors, utilizing the provided options including the custom timeout.

### Actual Behavior
The operation fails with the following error:
```
PermissionDeniedError: Error code: 403 - {'detail': 'Must pass an astradb token in the astra-api-token header'}
```

### Additional Information
- Removing the `with_options` method call and directly using `files.create()` without any options works correctly, suggesting an issue with how headers or tokens are managed when `with_options` is used.
- OpenAI version: 1.21.2
- Python version: 3.10.13
- Operating System: macOS 14.1.1

**Comment by phact** [comment]
Hi thanks for sharing your issue!

Please set your api token as an environment variable in your `.env` file:

```
# https://astra.datastax.com/ --> tokens --> administrator user --> generate
export ASTRA_DB_APPLICATION_TOKEN="AstraCS..."
```

or directly in python if you prefer
```
env.environ['ASTRA_DB_APPLICATION_TOKEN'] = 'AstraCS...'
```

**Comment by phact** [comment]
Hi @VRSEN,

Checking in, did this help?

--Seb

**Comment by VRSEN** [comment]
Hey @phact, no last time I tested it, it didn't help. However, this did:

```python
from openai import OpenAI
from streaming_assistants import patch
client = patch(OpenAI(default_headers={
    'astra-api-token': os.environ['ASTRA_DB_APPLICATION_TOKEN'],
  }
))
```

**Comment by phact** [comment]
Interesting, we pull it in the patch here:

https://github.com/phact/streaming-assistants/blob/main/streaming_assistants/patch.py#L492

but we only do it for the calls that should technically need it (calls that require database persistence like messages, threads, assistants, etc.). Completions for example, don't need persistence so we don't look for the env var. 

It's possible that there's a path we missed. Do you remember exactly what you were running to get the error?

**Comment by VRSEN** [comment]
I was running this on my custom framework [Agency-Swarm v0.1.7](https://github.com/VRSEN/agency-swarm), which uses the `with_options` method to create files as mentioned in the issue. Here’s an example of setting up a basic agent:

```python
from openai import OpenAI
from streaming_assistants import patch
from agency_swarm import Agent, Agency

client = patch(OpenAI(default_headers={
    'astra-api-token': os.environ['ASTRA_DB_APPLICATION_TOKEN'],
    "OpenAI-Beta": "assistants=v1"
}))

ceo = Agent(name="CEO",
            description="Responsible for client communication, task planning, and management.",
            instructions="Please communicate with users and other agents.",
            model="anthropic/claude-3-haiku-20240307",
            files_folder="./files",
            tools=[])

agency = Agency([ceo])
```

Ensure you have files in your files folder. Removing `'astra-api-token': os.environ['ASTRA_DB_APPLICATION_TOKEN']` from the headers will cause the setup to fail.

**Comment by phact** [comment]
>     "OpenAI-Beta": "assistants=v1"

There is no way of overriding the OpenAI-Beta header once you've gone above sdk `v1.21.0`
The sdk will stomp your default header (which makes sense because it's using all the new types).

I'll test this again once we ship v2 support.

**Comment by phact** [comment]
fixed in the client
