### ISSUE TITLE
API Error When Assistants Do Not Utilize Attached Tools

### ISSUE THREAD

**Issue by VRSEN** [datastax/astra-assistants-api#27]
### Description
When adding tools to an assistant, the API throws an error if the assistant does not utilize them. In OpenAI, assistants can choose whether to use tools or not. This issue originates from the `threads.py create_run` method.

### Steps to Reproduce

1. Create an assistant with any custom tool. (function)
2. Ask the assistant to say "hi."
3. Observe the error: "Could not extract function arguments from LLM response, may have not been properly formatted. Consider retrying or use a different model."

### Expected Behavior
In OpenAI, tools can be attached to an assistant, allowing it to decide whether or not to use them. This autonomy in tool utilization is crucial for any agentic system.

### Actual Behavior
The operation fails with the error:
`ValueError("Could not extract function arguments from LLM response, may have not been properly formatted. Consider retrying or use a different model.")`

### Additional Information
* OpenAI version: 1.20.0
* Python version: 3.10.13
* Streaming assistants version: 0.16.0
* Operating System: macOS 14.1.1

**Comment by phact** [comment]
Working on this now

**Comment by phact** [comment]
Fix here - https://github.com/datastax/astra-assistants-api/pull/29/commits/921f687816cd5ccd578c395a276ce8c6a886ac3e

Shipped in v0.1.20, live on the service.

@VRSEN feel free to try it on your end.

**Comment by phact** [comment]
@VRSEN should we close this one since it's been fixed for a while?
