### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by morfeusys** [datastax/astra-assistants-api#38]
If I create thread with `await this.openai.beta.threads.create()` then `await this.openai.beta.threads.retrieve(threadId)` fails with 

ERROR - Unexpected error: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 'tool_resources'), 'msg': 'Field required', 'input': ThreadObject(id='18f14d98-25c2-11ef-825c-0242ac110003', object='thread', created_at=1717870104000, metadata={})}

Why do you need any validations here that breaks API?

**Comment by phact** [comment]
Hi @morfeusys, welcome, thanks for submitting this!

I actually just ran into the same bug and have a fix that's currently being tested. Will update later today when we ship a fix.

**Comment by phact** [comment]
updated the test [here](https://github.com/datastax/astra-assistants-api/blob/main/tests/streaming-assistants/test_threads_v2.py#L6-L8)
green CI [here](https://github.com/datastax/astra-assistants-api/actions/runs/9454624213)
shipped [both to dockerhub and to the service] in: v0.2.4
