### ISSUE TITLE
AN INFINIT LOOP HOLE: astra-assistants (>=2.0.16,<3.0.0) is incompatible with streaming-assistants (0.18.7rc0)

### ISSUE THREAD

**Issue by Y055EF** [datastax/astra-assistants-api#60]
I can't seem to figure out the incompatibility between dependencies when downloading with poetry as recommended by the readme.md ,the problem is that astra-assistants and streaming-assistants both depend on different versions of httpx

Because no versions of astra-assistants match >2.0.16,<3.0.0
 and astra-assistants (2.0.16) depends on httpx (>=0.27.0,<0.28.0), astra-assistants (>=2.0.16,<3.0.0) requires httpx (>=0.27.0,<0.28.0).
And because streaming-assistants (0.18.7rc0) depends on httpx (>=0.26.0,<0.27.0), astra-assistants (>=2.0.16,<3.0.0) is incompatible with streaming-assistants (0.18.7rc0).
So, because astra-assistants-api depends on both streaming-assistants (0.18.7-pre) and astra-assistants (^2.0.16), version solving failed.

**Comment by phact** [comment]
Maybe I have an old v1 example still hanging around somewhere that's throwing you off?

**Comment by Y055EF** [comment]
I downloaded the toml file in the the main repository, I don't know if this the right one to use or not, my main use case is to run agency swarm agents with astra but I am struggling to do so, every time I download them some dependency compatibility error arises and when I ignore it and try  to run the examples in the repository I get the open ai error of not using their API key. note: I have the groq api key as well as astra db key in the .env and loaded

**Comment by phact** [comment]
Swing over to the discord and I'll help you get up and running. Sounds like an environment issue to be honest.

**Comment by phact** [comment]
https://discord.gg/MEFVXUvsuy

**Comment by phact** [comment]
Env issue resolved in discord
