### ISSUE TITLE
AsyncOpenAIWithDefaultKey incorrect inheritance

### ISSUE THREAD

**Issue by sa411022** [datastax/astra-assistants-api#72]
Version: 2.1.0.26 (client)
File: astra_assistants/async_openai_with_default_key.py

from openai import OpenAI
class AsyncOpenAIWithDefaultKey(OpenAI):

should be

from openai import **Async**OpenAI
class AsyncOpenAIWithDefaultKey(**Async**OpenAI):

so that the async functions such as ainvoke/astream will work correctly.

It seems that the code version on the repo was only updated to 2.1.0.19,
which does not contain this file,
so I submit this issue instead of submit a PR.

**Comment by phact** [comment]
2.1.1 released!

**Comment by sa411022** [comment]
The async functions work correctly after upgrading to 2.1.1, thanks!
