### ISSUE TITLE
Chat completion example for Python not working

### ISSUE THREAD

**Issue by cfdude** [datastax/astra-assistants-api#74]
https://github.com/datastax/astra-assistants-api/blob/main/examples/python/chat_completion/basic.py

This example looks like it was crafted for OpenAI but the model was changed to Anthropic which has different requirements and would not work as coded.

**Comment by phact** [comment]
Hi, thanks for filing this issue!

The point of Astra Assistants is to make an openai compatible service that works with any model. Did you try it?

The tests definitely work but I haven't run the examples in a while.

**Comment by cfdude** [comment]
When patch(OpenAI) is called in the code it will go through the process of creating the openai compatible service, but then you get errors in the console as the rest of the code won't function as coded.  From a learning perspective, if this is supposed to demonstrate a chat completion it does not do that.

**Comment by phact** [comment]
What's your exact error? You need to make sure you pass the anthropic API key by setting it as an environment variable.

**Comment by phact** [comment]
Here's my output:

$ poetry run python examples/python/chat_completion/basic.py
Patching OpenAI client, it will now communicate to Astra Assistants API: https://open-assistant-ai.astra.datastax.com/v1/
Learn more about Astra at: https://docs.datastax.com/en/astra-db-serverless/tutorials/astra-assistants-api.html
prompt> Draw an ASCII art kitten eating icecream
artist-anthropic/claude-3-sonnet-20240229>
Here's an ASCII art of a kitten eating ice cream:

```
             ,---.
            /(    )\
           ( \`  / )
            `-/=%\=`
              )== (
             /      \
            /.`\\/'/.\
           //' /\'/ \'\
          / /'       \'\
         / /'        / \
         \_\'       /   \
          \__)     (    (
           \__)     )    \
            \__)   /      \
             \__) /\       \
              \  / \       /
               \/   \     /
                    \ \ /
                     \///
                     //\\
                    //  \\
                    \\  //
                     \\//
                      \/
```
...
... 


Note, you can pass the anthropic API key as an environment variable:

> export ANTHROPIC_API_KEY='<key goes here>'

before your python comand

or use a .env file as directed in the [readme](https://github.com/datastax/astra-assistants-api/?tab=readme-ov-file#client-getting-started-)

**Comment by phact** [comment]
That's the OpenAI SDK complaining that your `OPENAI_API_KEY` env var is not set. Note, even when using anthropic the openai_api_key needs to be set to something, even if it's an invalid key. To make sure your .env file is getting picked up try the following in your code:

    import os
    print(os.environ['OPENAI_API_KEY']

if you want, try setting your keys directly in your code as follows:

    os.environ["OPENAI_API_KEY"] = "dummy"

**Comment by cfdude** [comment]
I think I have discovered the issue, I had renamed the .env.bkp files in the root and /client directory to just .env however the symlink in the root directory was still pointing to .env.bkp.  Once I ran:
`readlink astra-assistants-api/.env`
it pointed out the problem which I corrected with:
`ln -sf astra-assistants-api/client/.env astra-assistants-api/.env`
(above paths shortened for readability)

Once the symlink was fixed the .env file began loading correctly and the example is working.  Thanks @phact !

**Comment by phact** [comment]
Hooray! Glad you got to the bottom of it.
