### ISSUE TITLE
The Endpoint https://open-assistant-ai.astra.datastax.com/v1 isn't working

### ISSUE THREAD

**Issue by johnpg82** [datastax/astra-assistants-api#80]
Hi All, I was excited to try this product but it appears that the endpoint in the code is no longer working.

https://open-assistant-ai.astra.datastax.com/v1

https://open-assistant-ai.astra.datastax.com/

**Comment by phact** [comment]
:confused: can you share exactly what makes you say the endpoint is not working? Do you have a stack trace / error message?

**Comment by johnpg82** [comment]
Nevermind @phact . It's working it's just the landing page said 404 so I thought it wasn't working.
