### ISSUE TITLE
Ruff non-dev dependency

### ISSUE THREAD

**Issue by cbornet** [datastax/astra-assistants-api#83]
Ruff is a non-dev dependency of the client.
This is annoying as libraries that import astra-assistant (like LangFlow) can't use their own version of ruff.
Can ruff be made a dev dependency ? If it is needed at runtime, can it be made optional ? Or relax the version constraint ?

**Comment by phact** [comment]
It's actually used at runtime by the LSP tool but yes we can absolutely figure out how to make it optional or at least loosen restrictions on the version constraint.

**Comment by phact** [comment]
Tested up to the latest `ruff` and it works
Updated to `ruff = ">=0.6.2,<9.0.0"` in latest client.
